### ISSUE TITLE
Weather Banner

### ISSUE THREAD

**Issue by gulfemakkaya** [gulfemakkaya/Capstone-Project#1]
Value Proposition

As a User 
I want to see a list of my plants
so that I can get an overview.

​

## Description

![image](https://user-images.githubusercontent.com/118002402/213475277-319f9bc1-6070-4f62-a2d2-dee8b25fff33.png)

​

## Acceptance Criteria

- [ ] All plants are listed as cards.
- [ ] In a card, the name of the plant is written.
- [ ] In a card, the picture of the plant is shown.
- [ ] In a card, specific information is written.
- [ ] In a card, is a delete button.
- [ ] In a card, is watering information.
- [ ] ...
      ​

## Tasks

- [ ] Create an Array of Objects which contain information about the plants.
- [ ] Create a Component that displays the Objects

      ​

## Complexity

... (M)

**Comment by ThomasF85** [comment]
Nice first story with good complexity!
However, your app should not contain useless / dummy buttons or links. Please remove all useless buttons (e.g. the delete button) and the navigation bar items that don't have working links.
Also your acceptance criteria should contain all the work you want to do. I am missing the following there:
- A header with the name or title of my app and logo is displayed
- A navigation bar is displayed

Either include those acceptance criteria, or remove the header or navigation bar from your excalidraw.

**Comment by ThomasF85** [comment]
Looks good!
