### ISSUE TITLE
Styling Header

### ISSUE THREAD

**Issue by gulfemakkaya** [gulfemakkaya/Capstone-Project#11]
## Value Proposition

As a User 
I want to have a styled ui
so that my app has a better overview.
​

## Description

![image](https://user-images.githubusercontent.com/118002402/219040517-c6c13036-2258-48b3-8595-b0eadfc02fe4.png)

​

## Acceptance Criteria

- [ ] Display Header

      ​

## Tasks

- [ ] add styling to the body
- [ ] add styling to header component
- [ ] change the front from the name of the app

      ​

## Complexity

... (S)
