### ISSUE TITLE
Plant Card Add Button

### ISSUE THREAD

**Issue by gulfemakkaya** [gulfemakkaya/Capstone-Project#2]
## Value Proposition

As a User 
I want to add plants
so that I can expand my plant collection.

## Description

![image](https://user-images.githubusercontent.com/118002402/214281894-bfbdaf45-c175-47b9-a690-1504056e56a6.png)

​

## Acceptance Criteria

- [ ] The add button leads to a page where you can write in information about your new plant​
- [ ] The new plant page has a button that leads back to the main page
- [ ] In an input field, you can write the name of the plant
- [ ] In an input field, you can choose the place 
- [ ] In an input field, you can write the watering-time
- [ ] There is a submit button at the bottom of the page that saves your plant and creates a new card

## Tasks

- [ ] Create a Link component for the add page and go back link.
- [ ] Create a form component rendering all four inputs and a submit button.
- [ ] Write a handleSubmit function.
- [ ] The Submit Button creates a new Card with all the new information.
- [ ] The Submit leads to the main page and shows the new Plant Card.
      ​

## Complexity

... (L)

**Comment by AstridOttmann** [comment]
Does the new card has a function? Or is there just an empty card shown after you press the add-button?
Tasks: create a new card (empty?)

**Comment by NikRoe** [comment]
Hi there,

exactly what Astrid said and some additions / questions.

Is it intended that cards get created without any content at the beginning?

Is this truly a submit button or rather a button you click that shows a form afterwards where you can enter information for a new card and submit a new card with that information? If so, please mention this in your user story :) 

The navigation bar should be for navigating to different pages. You have two options:
- if you mean to have an icon in your navbar, this should link to a corresponding page where you can add new entries
- or you can have the button as part of the page itself and clicking it shows a form to add a new card with information

Hope this helps :)

**Comment by AstridOttmann** [comment]
Hey, looks good! 
Just a few notes: 
- is it possible to upload the picture right now? If not, remove the field
- just a proposal: As a User
I want to add plants
so that I can expand my plant collection
- me as a user, I wouldn't expect an add-button in the navbar (but that's only my opinion)
- in your tasks you could use terms as component, folder or file (for the pages), handleSubmit function

**Comment by AstridOttmann** [comment]
Topp!
