### ISSUE TITLE
Delete a Card

### ISSUE THREAD

**Issue by gulfemakkaya** [gulfemakkaya/Capstone-Project#3]
## Value Proposition

As a user
I want to delete cards from my list
so that I can decrease the number of plants on my list.
​

## Description

![image](https://user-images.githubusercontent.com/118002402/214267751-dc8f29a4-bc61-461a-ac95-f0aede448a23.png)

## Acceptance Criteria

- [ ] In every card is a delete button.
- [ ] The delete button renders the page and shows the updated version of the list
      ​

## Tasks

- [ ] create a delete button for every plant-card
- [ ] write an onClick function that deletes each card if clicked
- [ ] the deletion rerenders the page and shows only the available plants.

      ​

## Complexity

... (M)

**Comment by RobinWitt** [comment]
Just a small typo: In your second acceptance criteria it should say "reload" or "rerender" instead of "render".
Apart from that it looks good to me!

**Comment by gulfemakkaya** [comment]
Thanks Robin !
