### ISSUE TITLE
Edit Card

### ISSUE THREAD

**Issue by gulfemakkaya** [gulfemakkaya/Capstone-Project#9]
## Value Proposition

As a User 
I want to have morde detailed informations
so that I can track where the plant is and when I last watered it.
​

## Description

![image](https://user-images.githubusercontent.com/118002402/218982959-b580f136-d0e1-4fff-8fa9-f5dba0da4801.png)

​

## Acceptance Criteria

- [ ] In my card is a select field where I can select how much water the plant is going to need.
- [ ] In my card is a select field where I can select in which place the plant is standing.
- [ ] In my card is a select field where I can select how much light the plant is going to need.
- [ ] In my card is also an input field where I can note on which date I last watered the plant.
      ​

## Tasks

- [ ] In PlantCard.js create a form
- [ ] In that form create 3 section ffields with values.
- [ ] And one input field with the type "date"
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by Diren-T** [comment]
looks good for me!
the complexity should still specify :)
